<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SON</name>
   <tag></tag>
   <elementGuidId>f8ebec77-5068-436b-816b-2cefd1985a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='exCollapsingNavbar2x']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>727fbe9d-1661-4b03-b89f-b927f1ea6acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/son</value>
      <webElementGuid>bab12cf0-edbf-4fa3-b719-96a900d0714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>4eb5f399-337a-404a-9413-488258f76960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SON</value>
      <webElementGuid>db1dfb02-88de-4b3f-8439-e01d011a7606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exCollapsingNavbar2x&quot;)/ul[@class=&quot;nav navbar-nav navbar-nav-style&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>cf10f82e-c179-465b-8545-925f5d9f6520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='exCollapsingNavbar2x']/ul/li[3]/a</value>
      <webElementGuid>b827a16f-234a-407a-b931-548e7766313c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SON')])[2]</value>
      <webElementGuid>07368fe8-f7c6-4cb8-8206-3b2455f76030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NƯỚC HOA'])[2]/following::a[1]</value>
      <webElementGuid>4e471dc1-0fab-4595-896e-54c50e546f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[2]/following::a[2]</value>
      <webElementGuid>f664552a-6202-4cd1-8670-5af6226921f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son highend'])[2]/preceding::a[1]</value>
      <webElementGuid>0c01eae0-01c8-4e85-859f-353d999e5684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son Hot trend'])[2]/preceding::a[2]</value>
      <webElementGuid>44c6acff-b4d2-472a-90a0-1eea42014fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/son')])[4]</value>
      <webElementGuid>5758d22d-db66-4a0a-b4dc-d4844bbfeba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>d4d950f3-8d4c-4995-8cc4-69816fa947d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/son' and (text() = 'SON' or . = 'SON')]</value>
      <webElementGuid>e883ddbb-152b-4b18-a337-ff0d45782a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
