<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ThemGioHang</name>
   <tag></tag>
   <elementGuidId>a9cb862b-c364-4fa9-9a2e-3848ba973803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-lg.btn-style.btn-cart.add_to_cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>574e5d81-5289-4888-bfab-ed8a2a1f9538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f597d8d3-28ee-4ea0-8e60-d37dcab8508d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-style btn-cart add_to_cart</value>
      <webElementGuid>6238b312-7dbf-4a9f-ac4e-4f94fa18bc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>96f426f9-2d26-461d-9734-523861b07601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>d8d0bcba-423e-4c5b-8acf-c6e44746cd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-form&quot;)/div[@class=&quot;form-group btn-form-product product__quantity&quot;]/div[@class=&quot;abctest&quot;]/div[@class=&quot;custom-btn&quot;]/button[@class=&quot;btn btn-lg btn-style btn-cart add_to_cart&quot;]</value>
      <webElementGuid>73c6310f-9b7a-4f71-b346-923dff09815e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>cc5fa2d9-121e-47c9-a9f0-c6ecf78150fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-to-cart-form']/div[3]/div/div[2]/button</value>
      <webElementGuid>47201073-5901-4c28-93bf-d5a4e7c40150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng:'])[1]/following::button[1]</value>
      <webElementGuid>d44b3c50-9f5f-45f1-bbe0-e5865e75ba55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phân loại'])[1]/following::button[1]</value>
      <webElementGuid>4aec703c-b393-41b6-a9d0-0e3994bf44bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share:'])[1]/preceding::button[1]</value>
      <webElementGuid>386d6576-bf2f-4f91-92f0-0100d01315e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#romand #dewyful'])[1]/preceding::button[1]</value>
      <webElementGuid>36362832-b375-486c-b9b7-b86119636852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm vào giỏ']/parent::*</value>
      <webElementGuid>3a199d5f-d46c-4e71-bd1d-4ed669470eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>9972a3cb-722d-41fb-a6fd-2d11378da454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Thêm vào giỏ' and (text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>f2abc3d4-b1dc-4f34-bb03-999d86e67346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
