<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gia_180.000</name>
   <tag></tag>
   <elementGuidId>221e2d16-cef5-41f1-a15b-c7d9cf5986f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-new-price > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModal']/div/div/div[2]/div/div[2]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ad6d41e-31b2-4626-a8ff-8111f9c85f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>180.000 đ</value>
      <webElementGuid>d58839dd-635b-4b3a-a6a4-c459bf8083c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-body&quot;]/div[@class=&quot;product-new-price&quot;]/span[1]</value>
      <webElementGuid>5d1bb0fb-82c7-41cd-abba-6f3694a4ef69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div[2]/div/div[2]/div[2]/span</value>
      <webElementGuid>564c824e-8235-453b-b98e-68a1f3341340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son Tint Romand Dewyful Water Tint 5g - 03 If Rose'])[2]/following::span[1]</value>
      <webElementGuid>522d3e4b-e293-40a9-a225-ea2907b6cea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ hàng thành công'])[1]/following::span[1]</value>
      <webElementGuid>7d34bc52-a4f4-42df-a275-c7f0663cb126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp tục mua hàng'])[2]/preceding::span[1]</value>
      <webElementGuid>474a94c6-f546-4d17-8120-70d0e73ded74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiến hành thanh toán »'])[1]/preceding::span[1]</value>
      <webElementGuid>d2f9ef09-43cb-4670-9d27-b348720f0c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='180.000 đ']/parent::*</value>
      <webElementGuid>0fd57429-23cd-4c91-bbaf-524ca60bc757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div[2]/div[2]/span</value>
      <webElementGuid>51c079fb-6d93-4cf3-8913-d4803fb02559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '180.000 đ' or . = '180.000 đ')]</value>
      <webElementGuid>5c23df4a-680f-4d82-8e6e-3a8a19c61b7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
