<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TangSoLuongg</name>
   <tag></tag>
   <elementGuidId>572e1353-9102-4054-afe6-7d004f90d37d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.quantity__up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick=&quot;quantityChange('up')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9e24a92-a672-4a35-8c9b-c2d629721d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity__up</value>
      <webElementGuid>7df3176c-c8f3-4f59-8756-858f41b2619a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quantityChange('up')</value>
      <webElementGuid>3865bd94-34d5-46c8-9814-3f02b0e2d38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-form&quot;)/div[@class=&quot;form-group btn-form-product product__quantity&quot;]/div[@class=&quot;abctest&quot;]/div[@class=&quot;quantityabc&quot;]/span[@class=&quot;quantity__up&quot;]</value>
      <webElementGuid>cc832e98-afd6-4ede-a29d-333c48454490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick=&quot;quantityChange('up')&quot;]</value>
      <webElementGuid>eb11126f-868b-45e7-b975-ffb06706e401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-to-cart-form']/div[3]/div/div/span[2]</value>
      <webElementGuid>6030e301-a90f-494d-9094-af97a15ff7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng:'])[1]/following::span[2]</value>
      <webElementGuid>40fd0edd-67c8-42a9-b8bf-1ffc55879be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phân loại'])[1]/following::span[2]</value>
      <webElementGuid>0f9f3810-34e7-4789-980e-602fd7b8c0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào giỏ'])[1]/preceding::span[1]</value>
      <webElementGuid>c8fe0776-3cab-4835-b02d-679159b4e976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share:'])[1]/preceding::span[1]</value>
      <webElementGuid>89800fc6-f3ac-45ab-865c-3dc7bea40354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span[2]</value>
      <webElementGuid>460a6875-b1b2-48d8-9c1c-feea57efc7d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
