<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestTimkiem</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>461b6509-13c7-41af-81d1-75d75acd0782</testSuiteGuid>
   <testCaseLink>
      <guid>540e50f9-6ff7-47dd-b9b5-d7593b1f36e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>951f80ef-8e4c-4291-a923-e1a57c840b8c</id>
         <masked>false</masked>
         <name>timkiem</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TimKiem/TC01_Detrong</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d2e6970b-8abd-4bac-ac80-f93a7f4e4904</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Timkiem/DataTimKiem</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d2e6970b-8abd-4bac-ac80-f93a7f4e4904</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Timkiem</value>
         <variableId>951f80ef-8e4c-4291-a923-e1a57c840b8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce896e27-238b-481e-a9be-54bb63031abf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TimKiem/TC02_Nhapkhongdau</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9c630d8d-983c-4e59-88e3-7cee196bdf80</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-4</value>
         </iterationEntity>
         <testDataId>Data Files/Timkiem/DataTimKiem</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9c630d8d-983c-4e59-88e3-7cee196bdf80</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Timkiem</value>
         <variableId>7805d711-d394-413c-b1a7-6edc37871db1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aaefeeed-ed89-4105-b791-e0c066f53557</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TimKiem/TC03_Nhapkitulienquan</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>20821c58-d894-41bb-8d29-2a1de99cfcc0</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-7</value>
         </iterationEntity>
         <testDataId>Data Files/Timkiem/DataTimKiem</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>20821c58-d894-41bb-8d29-2a1de99cfcc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Timkiem</value>
         <variableId>0521cb45-b2a6-4976-a701-4fe09485ae09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f078473d-8456-4277-8c86-52efa90a52b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TimKiem/TC04_Nhapsailoichinhta</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0bd3f56d-86ac-4c8f-82a5-0799f8f40c87</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-9</value>
         </iterationEntity>
         <testDataId>Data Files/Timkiem/DataTimKiem</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0bd3f56d-86ac-4c8f-82a5-0799f8f40c87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Timkiem</value>
         <variableId>e3c7d4c9-ce18-4b2c-ae18-b8522f29216d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fdb2602-65f4-4393-957f-6641f2273657</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TimKiem/TC05_Timsanphambatki</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d291e27-65de-438b-a7b8-ce2459f9c190</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>10-11</value>
         </iterationEntity>
         <testDataId>Data Files/Timkiem/DataTimKiem</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3d291e27-65de-438b-a7b8-ce2459f9c190</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Timkiem</value>
         <variableId>61f49982-9920-4d11-8a54-00d6d0092239</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
