<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GiamSoLuongTrongGio</name>
   <tag></tag>
   <elementGuidId>7aef65f1-8332-4566-b9ea-6897df621647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.reduced_pop.items-count.btn-minus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[27]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b956b2e0-9305-4d64-b092-8e5ffceef865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var result = document.getElementById('qtyItem65446529'); var qtyItem65446529 = result.value; if( !isNaN( qtyItem65446529 ) &amp;&amp; qtyItem65446529 > 1 ) result.value--;return false;</value>
      <webElementGuid>a577090c-2933-4e99-8def-f3583fb54a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reduced_pop items-count btn-minus</value>
      <webElementGuid>decc7bdd-f5a5-4b93-be3a-2c558c3a0ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c7cd160-2575-4136-80d7-f635b25e8aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>–</value>
      <webElementGuid>d9484468-6f62-4631-8e62-d0103876b21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;main-cart-page main-container col1-layout&quot;]/div[@class=&quot;main container hidden-xs-fix&quot;]/div[@class=&quot;col-main cart_desktop_page cart-page&quot;]/div[@class=&quot;cart page_cart hidden-xs-down&quot;]/form[1]/div[@class=&quot;bg-scroll&quot;]/div[@class=&quot;cart-tbody&quot;]/div[@class=&quot;item-cart productid-65446529&quot;]/div[@class=&quot;a-center&quot;]/div[@class=&quot;input_qty_pr&quot;]/button[@class=&quot;reduced_pop items-count btn-minus&quot;]</value>
      <webElementGuid>a298484a-eabf-4c02-a8ff-4bd43b30095f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[27]</value>
      <webElementGuid>a5de11e7-64d0-4e75-a0cb-134e89998650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son Tint Romand Dewyful Water Tint 5g'])[1]/following::button[1]</value>
      <webElementGuid>bfbba382-c0af-49fe-8712-40a6b8f95166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xoá'])[1]/following::button[1]</value>
      <webElementGuid>7efb2cb0-9343-46ba-9c65-c3b0966ddf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[1]</value>
      <webElementGuid>d9286f25-620d-4408-a932-0a76fefcec17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/preceding::button[2]</value>
      <webElementGuid>267d75ef-59f1-4f4a-8e33-c9adf126eab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='–']/parent::*</value>
      <webElementGuid>b44db76d-6b50-4d49-bec2-edac606454ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>f8eaa379-4121-4d9e-980a-df68a87d923b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '–' or . = '–')]</value>
      <webElementGuid>96e1ec3d-2c05-46b3-a1e3-4b2382b795a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
