<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_180.000</name>
   <tag></tag>
   <elementGuidId>2d72c992-0673-40d1-9995-6eeb1069eb21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.totals_price.price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='shopping-cart-totals-table']/tfoot/tr/td[2]/strong/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85d04b81-21a3-4896-b007-94b1f6844bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totals_price price</value>
      <webElementGuid>5776ff15-a5e8-4582-8487-aa254b6e359f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>180.000₫</value>
      <webElementGuid>896c11d5-ca40-47c8-bea2-6200cd832286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-totals-table&quot;)/tfoot[1]/tr[1]/td[@class=&quot;a-right&quot;]/strong[1]/span[@class=&quot;totals_price price&quot;]</value>
      <webElementGuid>4642ca35-fea1-4fce-ad1c-4c5dd8ee7cb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-totals-table']/tfoot/tr/td[2]/strong/span</value>
      <webElementGuid>2adbd530-b627-44fc-a456-ba7640effe5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền'])[1]/following::span[1]</value>
      <webElementGuid>3d0ab86d-831c-4f29-a620-dc75407c7e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/following::span[1]</value>
      <webElementGuid>4e5e42c7-a15a-4613-8ead-f5bc90cd9217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiến hành đặt hàng'])[1]/preceding::span[1]</value>
      <webElementGuid>ea0ce7f9-e655-46c6-b89e-673b2aa8416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giỏ hàng của bạn'])[1]/preceding::span[2]</value>
      <webElementGuid>e932934a-124a-4d50-acca-46197209f80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/span</value>
      <webElementGuid>b778ecc7-1e45-44c2-8683-1c8eef5fe18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '180.000₫' or . = '180.000₫')]</value>
      <webElementGuid>b44efa76-90c9-4e1b-8fba-e00ff3488e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[2]</value>
      <webElementGuid>ed50c293-679b-4f4b-93e6-9f81012b8374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/following::span[2]</value>
      <webElementGuid>086bb8b4-0167-4ab5-bb3c-dbaad3fd6c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/preceding::span[1]</value>
      <webElementGuid>b3bddcf6-dc8b-4cc8-869f-c540acb06483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền'])[1]/preceding::span[3]</value>
      <webElementGuid>525d12b3-14a3-44f7-96ca-57d516fad6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span</value>
      <webElementGuid>13602441-5d74-41e7-b128-b70af1da821e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
