<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Capnhat</name>
   <tag></tag>
   <elementGuidId>1126ac62-1573-4d19-91f3-6071d1b2f7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_address_23894750 > #customer_address > div.form-group.clearfix > div.row > div.col-sm-12.col-xs-12 > button.btn.btn-lg.btn-style.article-readmore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0e0fdbc-b851-487b-9dd5-9920eae3d11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-style article-readmore</value>
      <webElementGuid>5a9ffd66-919b-47cb-9965-5a8302fa4bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>caba9c10-563c-4269-915a-c9abf71a1e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cập nhật địa chỉ</value>
      <webElementGuid>6aebecf5-320b-4ee3-9971-6034ad54be21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_address_23894750&quot;)/form[@id=&quot;customer_address&quot;]/div[@class=&quot;form-group clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-xs-12&quot;]/button[@class=&quot;btn btn-lg btn-style article-readmore&quot;]</value>
      <webElementGuid>eb5a11fb-c9a8-4cf8-8e8f-6aa2b3888e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[6]</value>
      <webElementGuid>9b959e8c-8ff8-4cbc-bae4-1932ba620882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='customer_address']/div[2]/div/div/button)[3]</value>
      <webElementGuid>12cc3696-0e08-4ca5-bfe6-65c692d795c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số điện thoại'])[3]/following::button[1]</value>
      <webElementGuid>af0012d1-e482-40f8-9cfe-cf5f5bcf25f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[3]/preceding::button[1]</value>
      <webElementGuid>77dad8b9-9504-4e39-9655-0cae255ae394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/form/div[2]/div/div/button</value>
      <webElementGuid>cb18b59a-c387-435c-8584-2c338f861523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Cập nhật địa chỉ' or . = 'Cập nhật địa chỉ')]</value>
      <webElementGuid>ca9f9411-c7d5-4c82-9a67-0f25ad1eb3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
