<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sua</name>
   <tag></tag>
   <elementGuidId>80151902-2466-4a94-821d-67d10bb6cb16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool_address_23894750 > p.btn-row > button.btn.btn-lg.btn-style.article-readmore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[31]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>815bfcf2-8c3a-4c96-90c1-7644bd62e48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-style article-readmore</value>
      <webElementGuid>603151a9-0d50-458e-9db3-01ec2d9ffd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc97727c-2ae7-4058-bb44-03f894056826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>967224d0-84b5-41cc-b661-6294b2a3effa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapseExample-23894750</value>
      <webElementGuid>360122e1-173a-4a53-aab2-941938f67079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3686af67-6202-4f7f-8dfe-9b1d47c3ea70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseExample-23894750</value>
      <webElementGuid>7ecb912f-37ed-4249-a9ae-59fdb30b2675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Sửa
									</value>
      <webElementGuid>23eddbc2-beac-4954-8a00-091d84fb5072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool_address_23894750&quot;)/p[@class=&quot;btn-row&quot;]/button[@class=&quot;btn btn-lg btn-style article-readmore&quot;]</value>
      <webElementGuid>394a5e07-63e9-4757-8688-5c722c3bb91e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[31]</value>
      <webElementGuid>c37c1c90-4262-410c-874d-00ed055a01e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tool_address_23894750']/p/button</value>
      <webElementGuid>8981329f-64fb-4843-b292-1ef0d3bac1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Trang'])[1]/following::button[1]</value>
      <webElementGuid>bab75c8c-c205-424c-ba1b-a09cd64c439b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[2]/following::button[1]</value>
      <webElementGuid>d468cea6-a737-4d1d-af65-85dfc4051648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[2]/preceding::button[1]</value>
      <webElementGuid>7354b3df-1f70-49db-bb0a-5471f7bc3760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên'])[3]/preceding::button[2]</value>
      <webElementGuid>501e8edc-5e3a-4c32-993d-e22eddbe650c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/p/button</value>
      <webElementGuid>c3a280dd-83dc-4a15-8d85-4d99af371020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
										Sửa
									' or . = '
										Sửa
									')]</value>
      <webElementGuid>c014429a-b319-4bff-8770-d8c34548a0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
