<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thaydoisdt</name>
   <tag></tag>
   <elementGuidId>d945c790-21b3-4a68-af86-7930c9586deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_address_23894750 > #customer_address > div.clearfix > fieldset.form-group > input[name=&quot;PhoneNumber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='PhoneNumber'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25c3a1ff-9426-4e85-bce7-54f25e421e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95f41e09-9d89-447b-bf87-b1cb38ddf59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number-sidebar-z</value>
      <webElementGuid>43c0dde9-0c2b-4659-b6cb-2f4a3d07ffef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>45cda105-cb79-44eb-8ee5-949779c0f370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>09864543247</value>
      <webElementGuid>16765c06-2ab5-47f3-8deb-c8c01db03e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_address_23894750&quot;)/form[@id=&quot;customer_address&quot;]/div[@class=&quot;clearfix&quot;]/fieldset[@class=&quot;form-group&quot;]/input[@class=&quot;form-control number-sidebar-z&quot;]</value>
      <webElementGuid>cafa10a2-62ac-4dab-86d3-8679afa5431f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='PhoneNumber'])[3]</value>
      <webElementGuid>5204be06-3b36-4bac-8c31-646e5293cd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='customer_address']/div/fieldset[9]/input)[3]</value>
      <webElementGuid>7d93dc47-f4ea-4025-8aec-6b828b0b195c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/form/div/fieldset[9]/input</value>
      <webElementGuid>dde5f4a3-423d-4ec0-b92d-aa6beb90e52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'PhoneNumber']</value>
      <webElementGuid>ea97ac09-f6a3-4494-ae8f-16e0d2f8ab88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
