<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ThaydoiHo</name>
   <tag></tag>
   <elementGuidId>0cec73f7-da5d-4d45-9996-66186c9205a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_address_23894750 > #customer_address > div.clearfix > fieldset.form-group > input[name=&quot;LastName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='LastName'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2db0c25-fe83-4445-8c46-92cb14fd2ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19ce1ab0-7fb1-4947-93a3-4f98e0ad555a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d76c25a-1142-48d1-aba8-fa20821dfd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>e4f656f9-df9a-4b2c-b3d6-65b41b4ee8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nguyễn</value>
      <webElementGuid>f1c70ea1-bb3d-43c0-8154-c52a4236e801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_address_23894750&quot;)/form[@id=&quot;customer_address&quot;]/div[@class=&quot;clearfix&quot;]/fieldset[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a01bdce4-4889-4ce8-8b54-46fa0e363295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='LastName'])[3]</value>
      <webElementGuid>48ce9352-0be9-4e8e-adbc-e46c5d44eae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='customer_address']/div/fieldset[2]/input)[3]</value>
      <webElementGuid>a0bdf81b-db9c-42e5-b26e-80c0469ec5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/form/div/fieldset[2]/input</value>
      <webElementGuid>039e6a8b-ca6f-45b3-9aaa-cf2b942c6cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'LastName']</value>
      <webElementGuid>13a0dbe1-8683-4665-9a12-8be714b88de8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
