<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ThaydoiCongty</name>
   <tag></tag>
   <elementGuidId>c43eb24c-ff44-4a7b-bfaf-e53e6cfbbcaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_address_23894750 > #customer_address > div.clearfix > fieldset.form-group > input[name=&quot;Company&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='Company'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>385c67b0-6bfd-4940-8995-69bb157d0954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1b47339-bc6c-4b52-8e65-06bbab302896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a624d174-7422-4177-912f-b20289d2b333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>1726c7fc-e282-4316-a84d-e47f9cbcaf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_address_23894750&quot;)/form[@id=&quot;customer_address&quot;]/div[@class=&quot;clearfix&quot;]/fieldset[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>2cced9ed-64ec-43df-a264-e5b7454d57de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='Company'])[3]</value>
      <webElementGuid>6fc5b3f9-6515-438f-bcd3-41b46af00599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='customer_address']/div/fieldset[3]/input)[3]</value>
      <webElementGuid>37c7f231-e5d3-41c2-989e-13c0c8c1792d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/form/div/fieldset[3]/input</value>
      <webElementGuid>72977e18-f12e-49f4-8872-502ffb86d703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Company']</value>
      <webElementGuid>f22c3dfd-7af7-492f-8b2a-41b532e4cf09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
