<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ThaydoimaZip</name>
   <tag></tag>
   <elementGuidId>d8664e5c-8b6f-41f3-8834-87477d308a16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_address_23894750 > #customer_address > div.clearfix > fieldset.form-group > input[name=&quot;Zip&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='Zip'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c87899f6-4f19-4bfb-902f-50c123bbb242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2530534c-f879-432c-ae3c-1c0f91437db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>440eb5fa-7932-4f96-9991-007537dfc466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>9d5735f2-3cb8-4212-9e5a-9f266ecd4333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_address_23894750&quot;)/form[@id=&quot;customer_address&quot;]/div[@class=&quot;clearfix&quot;]/fieldset[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e85ebb81-b99c-45ea-88ac-a30d6f6d4248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='Zip'])[3]</value>
      <webElementGuid>2d2cf61e-1a8d-43bf-9bd8-812cac4defc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='customer_address']/div/fieldset[8]/input)[3]</value>
      <webElementGuid>fa860ea9-6f51-44f4-83e5-d3100356bdfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/form/div/fieldset[8]/input</value>
      <webElementGuid>cd799ece-15a1-4a3b-bd29-de82b9117fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Zip']</value>
      <webElementGuid>dbd3f130-691b-43f2-9b6c-e4c3dd5fa3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
