<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhaptimkiem</name>
   <tag></tag>
   <elementGuidId>55196cc5-8fe2-4648-94f3-b2156c7935ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div/div[2]/form/div/span/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>72f7c584-2443-4bad-a7bc-1c9b3848ce84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>f9ac446d-dd3a-4299-839d-eddc8034ee8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a105857c-4473-4d90-9ca0-f50fc4d89df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;wrap-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-lg-6 col-xl-6 col-search&quot;]/form[@class=&quot;form-inline search-box-lg&quot;]/div[@class=&quot;input-group col-lg-12&quot;]/span[@class=&quot;input-group-btn btn-group-lg&quot;]/button[@class=&quot;btn btn-secondary btn-search-lg&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>1752be92-7973-4169-9077-7f98eb7b411a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div/div[2]/form/div/span/button/i</value>
      <webElementGuid>cc3580bd-aa7d-433e-833e-7e908cd8ca13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>56458db3-f991-415d-89de-cf86c13be0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
