<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdetrong</name>
   <tag></tag>
   <elementGuidId>328eef1f-735e-4e48-9c82-b175197ce9ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.title-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Nhập từ khóa để tìm kiếm sản phẩm')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c38ef02-d81b-4c17-9b4d-9b621aeb6290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>83b01976-a30e-4b4d-89a2-97a70dbefa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-box</value>
      <webElementGuid>b145dded-f108-4caf-a9b5-7846890c753e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nhập từ khóa để tìm kiếm sản phẩm </value>
      <webElementGuid>b069eb58-880d-412a-a8bc-0aa8b092da6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;search-main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/h2[1]/a[@class=&quot;title-box&quot;]</value>
      <webElementGuid>4d0c7796-48b7-4140-845d-8c65ef28f0f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nhập từ khóa để tìm kiếm sản phẩm')]</value>
      <webElementGuid>d393a7c5-a656-4a00-9d79-951bd33b0792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Kết quả tìm kiếm với từ khóa ', '&quot;', '', '&quot;', '')])[1]/following::a[1]</value>
      <webElementGuid>014ce9ef-7856-4ebc-a874-c3039e7f9766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[3]/following::a[1]</value>
      <webElementGuid>7ab28a9b-f114-4863-aed5-40c5acd3ec2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm'])[1]/preceding::a[1]</value>
      <webElementGuid>462ea4e6-d008-4e1c-80f8-1b04fe4cec2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='myphamkissme@gmail.com'])[1]/preceding::a[3]</value>
      <webElementGuid>c3d10c44-8b5b-49d3-80d5-1862749eb9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nhập từ khóa để tìm kiếm sản phẩm']/parent::*</value>
      <webElementGuid>f8be64e8-d15d-4953-9e7d-8d8301e655bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>f0d861a3-ad45-4d48-ae9a-db01b1efcf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>2947ad90-dcbc-416b-a165-fbb914ce641c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Nhập từ khóa để tìm kiếm sản phẩm ' or . = 'Nhập từ khóa để tìm kiếm sản phẩm ')]</value>
      <webElementGuid>89b2efd2-9be9-4996-bf93-8c4a4bf5e782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
