<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Ketquatimkiem</name>
   <tag></tag>
   <elementGuidId>3eb32b21-2816-4c7a-a0f2-8bab933212f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[3]/following::strong[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>72075aa5-e13b-48bf-b3fe-672ffaaec9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kết quả tìm kiếm với từ khóa &quot;&quot;</value>
      <webElementGuid>d2cc1e77-258c-47c0-801a-9c041c311ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;bread-crumb&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/ul[@class=&quot;breadcrumbs&quot;]/li[2]/strong[1]</value>
      <webElementGuid>06e51ff1-6120-4daf-8fb3-904b58490335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[3]/following::strong[1]</value>
      <webElementGuid>4bfc72c4-d2a6-45f6-b43e-89ba235d16c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký}}'])[1]/following::strong[1]</value>
      <webElementGuid>908bd434-a7af-4f59-99f2-d962cc475f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm'])[1]/preceding::strong[1]</value>
      <webElementGuid>90a64dee-bd8b-4077-96ba-a855c0ebecf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='myphamkissme@gmail.com'])[1]/preceding::strong[1]</value>
      <webElementGuid>c2ceb334-1142-41e8-b6aa-48d48cfe8dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kết quả tìm kiếm với từ khóa &quot;&quot;']/parent::*</value>
      <webElementGuid>20a8a2d6-0767-4b86-b1e1-4b985554680c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>3be02d17-2ca2-4c77-b5fa-cb643d682d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Kết quả tìm kiếm với từ khóa &quot;&quot;' or . = 'Kết quả tìm kiếm với từ khóa &quot;&quot;')]</value>
      <webElementGuid>41c5c16f-0563-4d80-bc0e-ee39f90ca848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
